services:
  accountingdb:
    image: postgres:12
    container_name: accountingdb
    restart: unless-stopped
    profiles:
      - staging
    environment:
      POSTGRES_USER: ${PGUSER:-user}
      POSTGRES_PASSWORD: ${PGPASSWORD:-password}
      POSTGRES_DB: ${PGDATABASE:-accounting}
    ports:
      - "${PGPORT:-5435}:5432"
  vh-srv-accounting:
    image: "${IMAGE_NAME}"
    container_name: 'vh-srv-accounting'
    restart: unless-stopped
    env_file: .env
    cpus: '0.5'
    mem_limit: 250M
    ports:
      - "8190:8190"
networks:
  default:
    external:
      name: vh
